### PR TITLE
Use absolute directory for root.

### PR DESCRIPTION
**Pull request by spxtr**
Otherwise you get some really confusing errors.

### CODE REVIEW

**Comment by mikedanese** [comment]
What are the errors? Can you reconcile the change with this check? https://github.com/mikedanese/gazel/blob/master/gazel/config.go#L18-L20

**Comment by mikedanese** [comment]
Potentially move this into the body of NewVenderor and that check out of ReadCfg

**Comment by spxtr** [comment]
If you don't have the vendored packages in your `GOPATH` and root is `.`, you'll get this error for all vendored packages:
```
extract err: cannot find package "gopkg.in/yaml.v2" in any of:
	/goroot/src/gopkg.in/yaml.v2 (from $GOROOT)
	/gopath/src/gopkg.in/yaml.v2 (from $GOPATH)
```
I can look at reconciling.

**Comment by spxtr** [comment]
@mikedanese PTAL

**Pull request merged**
